### ISSUE TITLE
Go

### ISSUE THREAD

**Issue by NuttyJelly** [ScheiBig-Production/Always-Half-Full-theme#24]

**Comment by ScheiBig** [comment]
Just like with Zig, provided token list is very poor, consisting of:
- keywords,
- functions (methods only recognized on declaration),
- custom types (all treated the same) and build-in types,
-  build-in function utilities (colored as special functions),
-  function parameters (but not method receivers),
- variables / constants (this includes fields),
- operators,
- literals.

This means, that go official extension ignores fields, methods, channels and type types (interface / struct /typedef) from LSP (gopls provides those), and you might say that it could also provide receiver parameters, and map keys with ease (also, `true` / `false` / `iota` are threated as normal constants / not build-ins, and error as custom type not build-in).
