### ISSUE TITLE
[[ Core ] - window and menus ]

### ISSUE THREAD

**Issue by NuttyJelly** [ScheiBig-Production/Always-Half-Full-theme#46]

**Comment by ScheiBig** [comment]
Midnight theme is being put on hold

**Comment by ScheiBig** [comment]
- Midnight theme is considered done,
- GitLens is removed from scope of theme,
- remaining merge editor and port tokens (maybe few other?) tokens cannot be found in usage.
This concludes UI theme implementation for now
